name: lox-interpreter-ci

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    # if: contains(github.event.head_commit.message, 'To build')

    steps:
    - uses: actions/checkout@v2
    - name: building application
      run: |
        mkdir build
        cd build
        cmake ..
        make
        cd ..
        chmod +x run_tests.sh
        ./run_tests.sh ./build/interpreter
        rm -r build
